### PR TITLE
Upgrade all deps. Makes audit happy

### PR DESCRIPTION
**Pull request by ApacheEx**

### CODE REVIEW

**Comment by ApacheEx** [comment]
@raulfdm After checking this - I'd like to release a new version 2.2.0

**Comment by ApacheEx** [comment]
now this is good:

image


and build without warnings:

image

**Review by raulfdm — APPROVED** [review]
Looks good to me

**Comment by ApacheEx** [comment]
yeah, as I thought. I don't have access to run `npm publish`. 

I'd appreciate @morajabi if you could do so

**Pull request merged**
