### PR TITLE
fix(definition-types): accept custom string for all functions

### LINKED ISSUE #23: [TypeScript] Wrong Type Definition
Hello everyone 👋

## Expected Behavior

Be able to pass `size` (e.g. `1024px`) to all media query generators without any TypeScript complaint.

## Actual Behavior

The current type definition only allow us to pass the breakpoint keys (image below). If you pass a `size`, it'll work fine but the typescript compiler will complain about this unexpected value.

Screenshot 2020-01-24 at 11 57 34

## Steps to Reproduce the Problem

  1. Access this sandbox https://codesandbox.io/s/silent-forest-rgzhj
  1. Wait until loads completely
  1. Check `Box` component media query warning

## Specifications

  - Version: 2.1.2
  - Platform: any

### PR DESCRIPTION
**Pull request by raulfdm**
Closes #23 #21 

## Description

This PR adds a function overload for media.* functions that allow we pass a custom size via string or a specific media query name.

**First implementation**
image

**Secondimplementation**
image

**Result in VSCode**
image

### CODE REVIEW

**Comment by KesleyDavid** [comment]
Good morning folks, any release forecast?
I'm in the middle of a project, when I started coding the responsive I discovered this detail

**Review by ApacheEx — APPROVED** [review]
Hello, 

In fact, this PR has 3 new lines which solves the problem, rest is formatting by prettier I guess. But, anyways we need it on project level. So, it looks good for me to go.

**Comment by larissaiurk** [comment]
Hii! Thanks so much for this!

Seems like the PR for accept custom string has been merged, would it be possible to do a new release with those changes? Or already released and I didn't see...

**Comment by raulfdm** [comment]
Hey @larissaiurk .

To be really honest I think this package is not being maintained anymore.

Last year I'd merge a PR to solve that and it's indeed missing the release.
Despite the fact I'm set as a contributor, I cannot make releases. I've made a proposal of automating this flow (here https://github.com/morajabi/styled-media-query/issues/27) but it never got answered.


https://github.com/morajabi/styled-media-query/issues/23#issuecomment-678968738

**Comment by KesleyDavid** [comment]
Hey, @larissaiurk @raulfdm 
I made an update and the necessary adjustments to work correctly in the typescript and made a publication.
I was only using it for my projects, but if you want to use it too

https://www.npmjs.com/package/styled-query

**Pull request merged**
