### PR TITLE
Add support for styled-components v3

### LINKED ISSUE #12: Reduce the bundle size

### PR DESCRIPTION
**Pull request by ApacheEx**
Resolves #12:
- Add support for styled-components v3.
- Reduce the bundle size
- Fix function doc

### CODE REVIEW

**Comment by morajabi** [comment]
Thanks a lot! I really don't know how I missed this!

**Comment by morajabi** [comment]
screen shot 2018-02-07 at 10 24 32 pm

**Comment by morajabi** [comment]
Thank you again for taking time to contribute, I really appreciate it! Your PR is published as `v2.0.2` to NPM 🎉 

I invited you to the repository as a collaborator, it means you **can** review PRs, and merge them without the need for my review. That obviously doesn't mean you have to do anything, it's open source, **no one has to** put the time in! :) But it's totally fine if you merged PRs without my review or anything.

**Comment by ApacheEx** [comment]
Wow, it's incredible. Thank you so much, I'm happy to help 👌😉

**Comment by morajabi** [comment]
@ApacheEx Thank you for helping! :)

**Pull request merged**
